#pragma once

const int DISPLAY_OFFSET_X = 10;
const int DISPLAY_OFFSET_Y = 10;

const int WND_WIDTH = 460;
const int WND_HEIGHT = 600;

const int Y_OFFSET = 2;
const int X_OFFSET = 2;

const int LINE_X_OFFSET = 10;
const int LINE_Y_OFFSET = 10;
const int LINE_HEIGHT = 20;

const int IMAGE_SIZE = 28;
const int WIDE_BUTTON_SIZE = IMAGE_SIZE * 3;
const int LONG_FIELD_WIDTH = 300;
const int CHECKBOX_WIDTH = LONG_FIELD_WIDTH / 2 - LINE_X_OFFSET / 2;
const int SHORT_FIELD_WIDTH = WIDE_BUTTON_SIZE / 2;
const int DROP_LIST_HEIGHT = 100;

const int TITLE_HEIGHT = IMAGE_SIZE + Y_OFFSET * 2;
const int TITLE_HEIGHT_WITH_OFFSET = LINE_Y_OFFSET * 2 + TITLE_HEIGHT;

const int LIST_WIDTH = WND_WIDTH - LINE_X_OFFSET * 2;
const int LIST_WIDTH_SHORTED = LIST_WIDTH - IMAGE_SIZE - LINE_X_OFFSET;

const int RECORD_WIDTH = LIST_WIDTH - LINE_X_OFFSET * 2;
const int RECORD_WIDTH_SHORTED = LIST_WIDTH_SHORTED - LINE_X_OFFSET * 2;
const int RECORD_HEIGHT = 140;

const int WND_CLIENT_HEIGHT = WND_HEIGHT - TITLE_HEIGHT_WITH_OFFSET;

const int NOTIFICATION_WIDTH = 300;
const int NOTIFICATION_HEIGHT = 150;

const COLORREF UPCOMING_COLOR = RGB(130, 151, 235);
const COLORREF CURRENT_COLOR = RGB(240, 228, 52);
const COLORREF TO_LATE_COLOR = RGB(201, 30, 30);
const COLORREF DONE_COLOR = RGB(70, 229, 75);
const COLORREF END_COLOR = RGB(155, 155, 155);